[package]
name = "my-tls-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
anyhow = "1.0"
ring = "0.17"
p256 = { version = "0.13", features = ["ecdsa"] }
p384 = "0.13"
sha2 = "0.10"
